### ISSUE TITLE
Anyone working on a Nova 4 upgrade?

### ISSUE THREAD

**Issue by iHwy** [ctessier/nova-advanced-image-field#79]
Seeing some errors and not displaying correctly.

**Comment by ctessier** [comment]
Hi @iHwy

Thank you for your feedback

I didn't get the chance to test the package against Nova 4 yet.
Could you be more specific please?

Also, feel free to open a PR if you find anything you can fix.

Thank you
Clément

**Comment by LTKort** [comment]
We've got working in https://github.com/marshmallow-packages/nova-advanced-image

Can do an additional PR if needed

**Comment by ctessier** [comment]
Thank you for your message @LTKort, I appreciate it 😃 

I should soon be able to get working on the support for Nova 4. In the mean time, I merged a first contribution to a `2.x` branch. Do not hesitate to share your insight and contribution if you'd like to ;) 

Wish you a great day!

**Comment by Woeler** [comment]
So far I have been using the 2.x branch on a small personal project with resize and crop functionality and Nova 4. I have yet to run into problems. Works very well.

**Comment by Woeler** [comment]
Any news on a release? I still have the dev branches in my composer.json at the moment for my Nova4 projects. It works like a charm, but an official 2.0 would be cool. Are there any problems that need solving before a 2.0 can be tagged?

**Comment by ctessier** [comment]
Hi @Woeler,

I am currently working on the v2 with Nova 4 support. It will be out within a week or two!

Thank you for your patience 😉

**Comment by ctessier** [comment]
And it's out! Thank you guys for your support 👏
